python ../code/snapper.py dochtml newlog

python ../code/snapper.py --description | sed 's/^/# /' > ../Snapper.md
echo >> ../Snapper.md

echo '```' >> ../Snapper.md
python ../code/snapper.py --details >> ../Snapper.md
echo '```' >> ../Snapper.md
echo >> ../Snapper.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/snapper.docs.html`](./docs/snapper.docs.html), or visit <https://slimsuite.github.io/snapper/>.' >> ../Snapper.md
echo 'Documentation can also be generated by running Snapper with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../Snapper.md
echo >> ../Snapper.md
echo '## Introduction' >> ../Snapper.md
echo >> ../Snapper.md
grep -A 10000 genomes snapper.docs.Rmd >> ../Snapper.md

cp snapper.docs.html ../index.html
cp ../Snapper.md ../README.md
